# Default Configuration File for Picturebook
# Picturebook by Starza4TW
# Do NOT change this value. BAD THINGS WILL HAPPEN!
# Changing values outside the Filter node REQUIRES a server restart! A config reload will not change these values within the plugin!
# Do NOT change the configRevision node. BAD THINGS WILL HAPPEN!
configRevision: 2
allowMetrics: true
itemRenameTaskPeriod: 10
Filter:
  <black>: §0
  <dark_blue>: §1
  <dark_green>: §2
  <dark_aqua>: §3
  <dark_red>: §4
  <dark_purple>: §5
  <gold>: §6
  <orange>: §6
  <gray>: §7
  <dark_gray>: §8
  <blue>: §9
  <green>: §a
  <aqua>: §b
  <red>: §c
  <light_purple>: §d
  <yellow>: §e
  <white>: §f
  <obfuscated>: §k
  <magic>: §k
  <bold>: §l
  <strikethrough>: §m
  <underline>: §n
  <italic>: §o
  <reset>: §r
  <lenny>: ( ͡° ͜ʖ ͡°)
  <star>: ☆
  <3: ❤
  <comet>: ☄
  <radioactive>: ☢
  <peace>: ☮
  <yin-yang>: ☯
  <snowflake>: ❄