# Default Configuration File for Picturebook
# Picturebook by Starza4TW

# Do not Change/Mess with/Remove/etc. this line! BAD THINGS WILL HAPPEN!
configRevision: 1

Filter:
  <black>: §0
  <dark_blue>: §1
  <dark_green>: §2
  <dark_aqua>: §3
  <dark_red>: §4
  <dark_purple>: §5
  <gold>: §6
  <orange>: §6
  <gray>: §7
  <dark_gray>: §8
  <blue>: §9
  <green>: §a
  <aqua>: §b
  <red>: §c
  <light_purple>: §d
  <yellow>: §e
  <white>: §f
  <obfuscated>: §k
  <magic>: §k
  <bold>: §l
  <strikethrough>: §m
  <underline>: §n
  <italic>: §o
  <reset>: §r
  <lenny>: ( ͡° ͜ʖ ͡°)
  <star>: ☆
  <3: ❤