name: Picturebook
description: Chat filter that replaces keywords with definable replacements. Built for SpigotMC.
author: Starza4TW
website: transcendencegaming.net
version: 1.3.0.1
main: com.starza4tw.picturebook.Main
commands:
  picturebook:
    description: Base Command for the Picturebook plugin.
    usage: /picturebook
    aliases: [pb]
permissions:
  picturebook.*:
    description: Gives access to all commands found in Picturebook.
    children:
      picturebook.chatfilter: true
      picturebook.commandfilter: true
      picturebook.command: true
      picturebook.list: true
      picturebook.version: true
      picturebook.add: true
      picturebook.reload: true
      picturebook.remove: true
  picturebook.chatfilter:
    description: Changes player's chat using Picturebook's chat filters.
    default: true
  picturebook.commandfilter:
    description: Changes player's commands using Picturebook's chat filters.
    default: true
  picturebook.command:
    description: Allows players to use the base Picturebook command.
    default: true
  picturebook.list:
    description: Allows players to view the Filter List.
    default: true
  picturebook.version:
    description: Allows players to check Picturebook's version as well as other basic information.
    default: true
  picturebook.add:
    description: Allows players to add replacements to the Filter List.
    default: op
  picturebook.reload:
    description: Allows players to reload Picturebook's config.
    default: op
  picturebook.remove:
    description: Allows players to remove replacements from the Filter List.
    default: op